### PR TITLE
Added UserID getter to Session class

### PR DESCRIPTION
**Pull request by georgerb**

### CODE REVIEW

**Comment by georgerb** [comment]
Solves #45

**Comment by mborkunov** [comment]
I agree. This will be helpful for our purposes as well

**Comment by georgerb** [comment]
Is this project still alive and accepting PRs?

**Comment by flotho** [comment]
Hi,
Could you please give me an example of your specific need?
Actually, regarding to different Odoo API version, UID must be passed in differently and passing it in the context should be enough from my point of view.
regards

**Comment by flotho** [comment]
Hi, do you still interested in merging this PR ?
regards

**Pull request merged**
